# Generated by Django 3.2.4 on 2021-06-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('Value 1', 'Key 1'), ('Value 2', 'Key 2')], max_length=255, verbose_name='Tipo')),
            ],
        ),
    ]
